### ISSUE TITLE
about hidden_dim

### ISSUE THREAD

**Issue by PAULYZHENG** [noahcao/Pixel2Mesh#20]
Could you please explain why set options.model.hidden_dim = 192? I didn't find the support in this paper.

Looking forward to your reply.

Best,
Paul

**Comment by ultmaster** [comment]
Because in the code the paper authors released, hidden size is set to 192:

https://github.com/nywang16/Pixel2Mesh/blob/37cd58710a65ab452c00899443951dd2c2cd0bb9/eval_testset.py#L30

To be clear, in another file, hidden size is set to 256:

https://github.com/nywang16/Pixel2Mesh/blob/37cd58710a65ab452c00899443951dd2c2cd0bb9/train.py#L35

Judging by this, the paper authors are also not sure what is the best hidden size. I guess that's why they didn't put it in paper.

By the way, emprically, we find that hidden size 192 and 256 yield similar results. So finally, we set it to 192 for efficiency.

**Comment by PAULYZHENG** [comment]
Thanks for your reply.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Do you know how to use their provided YAML files and pretrained weights downloaded from here to do the evaluation?
To my understanding, I should use the downloaded meta folder. Then use the provide pretrained weights.
The command I use is 
```
python entrypoint_eval.py --name xxx --options experiments/default/tensorflow.yml --checkpoint datasets/data/pretrained/vgg16-p2m.pth 
```
But it seems that it only generated some meaningless meshes. And the score is really low.
I am not sure what I did wrong.
![Screenshot from 2020-09-22 02-08-41](https://user-images.githubusercontent.com/57812785/93863819-de0eac00-fc78-11ea-91b5-0235f5b4487b.png)
